[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
solc = "0.8.24"
fs_permissions = [{ access = "read", path = "./broadcast" }]
gas_reports = ["Foo"]

[rpc_endpoints]
base = "${BASE_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
